[package]
name = "taskwarrior"
version = "0.1.2"
edition = "2024"
description = "Rust interface to taskwarrior 2 via taskwarrior-sys"

[dependencies]
taskwarrior-sys = { version = "0.1.2", path = "../taskwarrior-sys" }
